[package]
name = "hwp"
version = "0.1.0"
authors = ["Sangwon Ryu <bdboy090@naver.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfb = "0.3.1"
nom = "5.1.2"
hex-literal = "0.3.1"